name: Build Docker image and push to ghcr

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CrowdStrike
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in into GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and label Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/bigdata-com/bigdata-thematic-screener:latest, ghcr.io/bigdata-com/bigdata-thematic-screener:${{ github.event.release.tag_name }}
    - name: Run security scan
      uses: Bigdata-com/security-scan-containers@master
      with:
        image_name: ghcr.io/bigdata-com/bigdata-thematic-screener:latest
        falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
        falcon_client_secret: ${{ secrets.FALCON_CLIENT_SECRET }}
        falcon_region: ${{ secrets.FALCON_REGION }}
        fcs_version: "2.0.2"
    - name: Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/bigdata-com/bigdata-thematic-screener:latest,ghcr.io/bigdata-com/bigdata-thematic-screener:${{ github.event.release.tag_name }}
