name: Build Docker image and push to ghcr

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in into GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/bigdata-com/bigdata-thematic-screener:latest,ghcr.io/bigdata-com/bigdata-thematic-screener:${{ github.event.release.tag_name }}
